language: go

go:
  - 1.11.0

cache:
  directories:
    - $GOPATH

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -t ./...

script: dep ensure && make test
